[build]
                                                                                          
                                                   
                                                     
                                                           
rustflags = ["-Ctarget-cpu=native", "-Ctarget-feature=-avx512f", "-Cllvm-args=-align-all-functions=6"]
