"""Typed, auditable performance-optimization changesets."""

from .registry import HandlerRegistry, OperationHandler
from .types import (
    AppliedChangeSet,
    ChangeOperation,
    ChangeSetStatus,
    ConcreteEdit,
    GateResultRecord,
    ImpactScope,
    OperationResolution,
    PromoteStaticToConst,
    ProposedChangeSet,
    RegionKind,
    RegionRef,
    ReplaceCallSite,
    ReplaceFunctionBody,
    ReplaceSourceRegion,
    ResolvedChangeSet,
    RewriteBitfieldStruct,
    SymbolKind,
    SymbolRef,
    TriggerContext,
    ValidationResult,
)

__all__ = [
    "AppliedChangeSet",
    "ChangeOperation",
    "ChangeSetStatus",
    "ConcreteEdit",
    "GateResultRecord",
    "HandlerRegistry",
    "ImpactScope",
    "OperationHandler",
    "OperationResolution",
    "PromoteStaticToConst",
    "ProposedChangeSet",
    "RegionKind",
    "RegionRef",
    "ReplaceCallSite",
    "ReplaceFunctionBody",
    "ReplaceSourceRegion",
    "ResolvedChangeSet",
    "RewriteBitfieldStruct",
    "SymbolKind",
    "SymbolRef",
    "TriggerContext",
    "ValidationResult",
]
