[workspace]

[package]
name = "purebin_stage_a"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "optipng_stage_a"
path = "src/main.rs"

[dependencies]
optipnglib = { path = "../../../2_stage_a/crate", package = "optipng_0_7_7_cleaned" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
