"""Orchestration loop of the harness-gen agent.

    inventory → plan(LLM) → scaffold → codegen(LLM)
    → [build → smoke → coverage] with bounded LLM repair rounds

The LLM only ever produces (a) the JSON spec and (b) src/lib.rs (the
`ops()` registry + `gen_seeds`). Cargo.toml / rust-toolchain.toml and
the static src/main.rs CLI shell are emitted deterministically, and the
model + API endpoint come exclusively from Config/paths.conf via
utils.llm_client.LLMClient (no second LLM configuration anywhere here).
"""

from __future__ import annotations

import json
import logging
import re
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from . import gates, prompts
from .inventory import CrateInventory, scan_crate

logger = logging.getLogger(__name__)

# Trigger a coverage-extend round for internal (non-pub) own functions only
# when at least this many are unreached — a small cluster isn't worth an LLM
# round (and some internals are unreachable by design).
INTERNAL_EXTEND_MIN = 8

CARGO_TOML_TEMPLATE = """\
# Generated by script_c2rust/harness_gen — workload harness for {crate_name}.
# Contract: `harness gen-seeds <dir>` / `harness <op> <input> [iters]`;
# stdout carries only deterministic digest lines (W1-style oracle bytes).

[package]
name = "{harness_name}"
version = "0.1.0"
edition = "{edition}"
publish = false

[lib]
name = "{harness_name}"
path = "src/lib.rs"

[[bin]]
name = "harness"
path = "src/main.rs"

[dependencies]
{crate_name} = {{ path = "{crate_path}" }}

# Fair-build profile for later perf use (gates build the dev profile).
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
"""

# Static CLI shell — never touched by the LLM. All logic lives in
# src/lib.rs behind the `ops()` registry, so fuzz targets and this shell
# share one implementation of every operation.
MAIN_RS_TEMPLATE = """\
// Generated by script_c2rust/harness_gen — static CLI shell.
// Usage:  harness gen-seeds <dir>
//         harness <op> <input-file> [iters]
use std::env;
use std::fs;
use std::process::exit;

fn main() {{
    let args: Vec<String> = env::args().collect();
    match args.get(1).map(|s| s.as_str()) {{
        Some("gen-seeds") => {{
            let dir = match args.get(2) {{
                Some(d) => d,
                None => {{ eprintln!("usage: harness gen-seeds <dir>"); exit(2); }}
            }};
            if let Err(e) = fs::create_dir_all(dir) {{
                eprintln!("mkdir {{}}: {{}}", dir, e); exit(1);
            }}
            for line in {harness_name}::gen_seeds(dir) {{
                println!("{{}}", line);
            }}
        }}
        Some("gen-perf") => {{
            let dir = match args.get(2) {{
                Some(d) => d,
                None => {{ eprintln!("usage: harness gen-perf <dir>"); exit(2); }}
            }};
            if let Err(e) = fs::create_dir_all(dir) {{
                eprintln!("mkdir {{}}: {{}}", dir, e); exit(1);
            }}
            for line in {harness_name}::gen_perf(dir) {{
                println!("{{}}", line);
            }}
        }}
        Some(op) => {{
            let file = match args.get(2) {{
                Some(f) => f,
                None => {{ eprintln!("usage: harness <op> <input-file> [iters]"); exit(2); }}
            }};
            let data = match fs::read(file) {{
                Ok(d) => d,
                Err(e) => {{ eprintln!("read {{}}: {{}}", file, e); exit(1); }}
            }};
            let iters: u64 = args.get(3).and_then(|s| s.parse().ok()).unwrap_or(1);
            if iters == 0 {{ eprintln!("iters must be >= 1"); exit(2); }}
            match {harness_name}::ops().into_iter().find(|(name, _)| *name == op) {{
                Some((_, f)) => println!("{{}}", f(&data, iters)),
                None => {{ eprintln!("unknown op: {{}}", op); exit(2); }}
            }}
        }}
        None => {{
            eprintln!("usage: harness <gen-seeds <dir> | <op> <file> [iters]>");
            exit(2);
        }}
    }}
}}
"""


@dataclass
class GenReport:
    ok: bool
    harness_dir: str = ""
    spec: dict[str, Any] | None = None
    line_pct: float = 0.0
    fn_pct: float = 0.0
    uncovered: list[str] | None = None
    llm_calls: int = 0
    failure: str = ""


class HarnessGenAgent:
    def __init__(self, project_dir: Path, out_root: Path | None = None,
                 model: str | None = None,
                 min_line: float = 60.0, min_fn: float = 70.0,
                 max_repairs: int = 6, cov_rounds: int = 2,
                 skip_cov: bool = False, perf_repairs: int = 3,
                 max_op_repairs: int = 1):
        self.project_dir = Path(project_dir).resolve()
        # default: dataset_trans_process/<proj>/workloads/harness_gen/
        self.out_root = (Path(out_root).resolve() if out_root else
                         self.project_dir.parent / "workloads" / "harness_gen")
        self.model = model
        self.min_line, self.min_fn = min_line, min_fn
        self.max_repairs = max_repairs
        # Repair attempts one operation may cost before it is dropped instead.
        # 1 = give it a single retry, then keep the rest of the harness.
        self.max_op_repairs = max_op_repairs
        self.cov_rounds = cov_rounds
        self.skip_cov = skip_cov
        # gate D (gen_perf runs) is a SEPARATE phase with its OWN budget so the
        # build/smoke/coverage oscillation of activity A can't starve it.
        self.perf_repairs_max = perf_repairs
        self.llm_calls = 0

    # ── LLM plumbing ────────────────────────────────────────────────

    def _make_llm(self, logs_dir: Path):
        from Config.paths import get_path
        from utils.llm_client import LLMClient
        model = self.model or get_path("DEFAULT_LLM_MODEL")
        if not model:
            raise RuntimeError("DEFAULT_LLM_MODEL missing from Config/paths.conf")
        logs_dir.mkdir(parents=True, exist_ok=True)
        return LLMClient(model,
                         transcript_path=logs_dir / "transcript.log",
                         cache_path=logs_dir / "cache.jsonl",
                         timeout=180)

    def _chat(self, llm, system: str, user: str, phase: str) -> str:
        self.llm_calls += 1
        logger.info("[harness_gen] LLM call #%d (%s)", self.llm_calls, phase)
        out = llm.chat(system, user, meta={"phase": phase,
                                           "project": self.project_dir.name})
        if not out:
            raise RuntimeError(f"LLM returned empty completion at phase {phase}")
        return out

    # ── scaffold ────────────────────────────────────────────────────

    def _scaffold(self, inv: CrateInventory, harness_name: str) -> Path:
        hdir = self.out_root / harness_name
        (hdir / "src").mkdir(parents=True, exist_ok=True)
        (hdir / "Cargo.toml").write_text(CARGO_TOML_TEMPLATE.format(
            crate_name=inv.crate_name, harness_name=harness_name,
            edition=prompts.HARNESS_EDITION,
            crate_path=str(inv.crate_dir)), encoding="utf-8")
        (hdir / "src" / "main.rs").write_text(
            MAIN_RS_TEMPLATE.format(harness_name=harness_name),
            encoding="utf-8")
        # The dep crate may need nightly features → pin the same toolchain.
        if inv.toolchain_file:
            shutil.copyfile(inv.toolchain_file, hdir / "rust-toolchain.toml")
        return hdir

    # ── main loop ───────────────────────────────────────────────────

    def run(self) -> GenReport:
        inv = scan_crate(self.project_dir)
        if not inv.fns:
            return GenReport(False, failure=f"no `pub extern \"C\" fn` found "
                                            f"in {self.project_dir}")
        logger.info("[harness_gen] crate=%s fns=%d structs=%d",
                    inv.crate_name, len(inv.fns), len(inv.structs))

        logs_dir = self.out_root / "logs"
        llm = self._make_llm(logs_dir)

        # ---- plan --------------------------------------------------
        spec = self._plan(llm, inv)
        harness_name = re.sub(r"[^a-z0-9_]", "_", spec["harness_name"].lower())
        spec["harness_name"] = harness_name
        hdir = self._scaffold(inv, harness_name)
        logger.info("[harness_gen] spec: %s ops=%s", harness_name,
                    [op["name"] for op in spec["operations"]])

        # ---- codegen -----------------------------------------------
        raw = self._chat(llm, prompts.CODEGEN_SYSTEM,
                         prompts.codegen_user(inv, spec), "codegen")
        lib_rs = prompts.extract_rust(raw)
        if not lib_rs:
            return GenReport(False, failure="codegen: no ```rust block in reply")

        # ---- gate loop ----------------------------------------------
        repairs = 0
        cov_rounds_used = 0
        cov = gates.CovResult(True)          # placeholder when skip_cov
        # Fix C: checkpoint the last build+smoke-passing (lib.rs, spec). A
        # later coverage-extend round can break a WORKING harness, and the
        # bounded repair loop may fail to recover (hard projects oscillate
        # build↔smoke and burn the budget). On exhaustion, revert to this
        # checkpoint and accept it — coverage is a soft target, a working
        # harness that finds the hot kernels beats no harness at all.
        last_good_lib_rs: str | None = None
        last_good_spec: dict[str, Any] | None = None
        reverted = False
        op_failures: dict[str, int] = {}
        while True:
            (hdir / "src" / "lib.rs").write_text(lib_rs, encoding="utf-8")

            # c2rust code is written for RELEASE semantics: it relies on
            # wrapping arithmetic and x86-tolerated unaligned reads. A debug
            # build with debug-assertions/overflow-checks ON makes the LIBRARY
            # itself panic on its own legitimate ops (e.g. libzahl zstr.rs
            # misaligned u16 read, integer overflow) → false smoke failures.
            # Build/smoke with those checks OFF to match how the crate runs.
            ok, feedback = gates.gate_build(
                hdir, rustflags="-C debug-assertions=off -C overflow-checks=off")
            stage = "build"
            if ok:
                ok, feedback = gates.gate_smoke(hdir, spec)
                stage = "smoke"
                if ok:                       # Fix C: checkpoint working harness
                    last_good_lib_rs = lib_rs
                    last_good_spec = json.loads(json.dumps(spec))
            # On revert (Fix C) skip coverage entirely — a build+smoke-passing
            # harness is accepted regardless of the soft coverage target (even
            # coverage-infra failures must not block it).
            if ok and not self.skip_cov and not reverted:
                cov = gates.gate_coverage(hdir, inv, spec,
                                          self.min_line, self.min_fn)
                if cov.error:
                    ok, feedback, stage = False, cov.error, "coverage-infra"
                # Extend when exported coverage is below the (hard) gate, OR
                # when a meaningful cluster of INTERNAL own functions is never
                # reached (soft signal — these hold the real hot kernels;
                # exported ok stays the pass condition). Bounded by cov_rounds.
                elif (not cov.ok) or len(cov.uncovered_internal) >= INTERNAL_EXTEND_MIN:
                    logger.info("[harness_gen] coverage line=%.1f%% fn=%.1f%% "
                                "(need %.0f/%.0f) uncov_exported=%d "
                                "uncov_internal=%d/%d",
                                cov.line_pct, cov.fn_pct, self.min_line,
                                self.min_fn, len(cov.uncovered),
                                len(cov.uncovered_internal), cov.internal_total)
                    if cov_rounds_used >= self.cov_rounds:
                        # accept with a warning — coverage is a soft target
                        logger.warning("[harness_gen] coverage-extend rounds "
                                       "exhausted; accepting (exported ok=%s, "
                                       "%d internal fns still unreached)",
                                       cov.ok, len(cov.uncovered_internal))
                        break
                    cov_rounds_used += 1
                    raw = self._chat(
                        llm, prompts.CODEGEN_SYSTEM,
                        prompts.coverage_user(inv, spec, cov.line_pct,
                                              cov.fn_pct, self.min_line,
                                              self.min_fn, cov.uncovered,
                                              cov.uncovered_internal, lib_rs),
                        f"coverage-extend-{cov_rounds_used}")
                    new_spec = prompts.extract_json(raw)
                    if new_spec and prompts.validate_spec(new_spec) is None:
                        new_spec["harness_name"] = harness_name
                        # Carry the drop decisions across: the code of a dropped
                        # op is still in lib.rs and still emits its seed, so a
                        # fresh spec without this list lets the smoke gate adopt
                        # it again. A round that deliberately RE-DESIGNS the op
                        # is unaffected — it lands in `operations`, and only
                        # unlisted ops are ever auto-adopted.
                        new_spec[gates.DROPPED_KEY] = list(
                            spec.get(gates.DROPPED_KEY) or ())
                        spec = new_spec
                    new_main = prompts.extract_rust(raw)
                    if not new_main:
                        return GenReport(False, spec=spec,
                                         failure="coverage-extend: no rust block")
                    lib_rs = new_main
                    continue

            if ok:
                break

            # One operation must not cost the harness. A repair rewrites the
            # WHOLE lib.rs, so every round spent on a stubborn op destabilises
            # the ops that already work — and when the budget runs out, the run
            # reverts the ENTIRE coverage extension, losing every good op to
            # save none.
            #
            # How much budget an op is worth depends on where it came from:
            #   * an op the PLAN designed is a main path of the library — the
            #     reason the harness exists. Give it a retry.
            #   * an op a COVERAGE round invented is a bonus. Measured across
            #     runs, these are also the fragile ones (crashing, or
            #     non-deterministic through some address/order-dependent
            #     value), and they arrive in batches: one round adopted nine,
            #     three of which were broken. Retrying each in turn burned the
            #     whole budget and reverted the batch — six good ops lost to
            #     save none of the three. So a bonus op that fails is dropped
            #     immediately.
            # Dropping takes it out of the spec, hence out of the smoke gate
            # and out of corpus/golden — the treatment such an op needs anyway.
            culprit = gates.failing_op(feedback)
            entry = next((o for o in spec["operations"]
                          if o["name"] == culprit), None) if culprit else None
            if entry is not None:
                allowance = 0 if entry.get("adopted") else self.max_op_repairs
                op_failures[culprit] = op_failures.get(culprit, 0) + 1
                if (op_failures[culprit] > allowance
                        and len(spec["operations"]) > 1):
                    # Through mark_dropped, not by hand: the smoke gate rebuilds
                    # the spec from the seeds the harness emits, so an op merely
                    # deleted here is adopted straight back on the next gate run
                    # — and dropping costs no repair budget, so that spins
                    # forever.
                    gates.mark_dropped(spec, culprit)
                    logger.warning(
                        "[harness_gen] dropping %s op `%s` — failed gate `%s`;"
                        " keeping the other %d op(s) rather than spending the"
                        " repair budget on it",
                        "coverage-adopted" if entry.get("adopted") else "planned",
                        culprit, stage, len(spec["operations"]))
                    continue          # re-gate without it; costs no repair

            repairs += 1
            if repairs > self.max_repairs:
                if last_good_lib_rs is not None and not reverted:
                    logger.warning("[harness_gen] repairs exhausted at gate "
                                   "`%s`; reverting to last build+smoke-passing "
                                   "harness (coverage extension abandoned)", stage)
                    lib_rs = last_good_lib_rs
                    # Drops made after the checkpoint still hold: the checkpoint
                    # restores the op list, not the reasons an op was rejected.
                    late_drops = [n for n in (spec.get(gates.DROPPED_KEY) or ())
                                  if n not in (last_good_spec.get(gates.DROPPED_KEY) or ())
                                  and all(o["name"] != n
                                          for o in last_good_spec["operations"])]
                    spec = last_good_spec
                    spec.setdefault(gates.DROPPED_KEY, []).extend(late_drops)
                    cov_rounds_used = self.cov_rounds   # no further extend
                    reverted = True
                    repairs = 0
                    continue
                return GenReport(False, harness_dir=str(hdir), spec=spec,
                                 llm_calls=self.llm_calls,
                                 failure=f"gate `{stage}` still failing after "
                                         f"{self.max_repairs} repairs:\n"
                                         f"{feedback[:2000]}")
            logger.info("[harness_gen] gate %s failed → repair %d/%d",
                        stage, repairs, self.max_repairs)
            raw = self._chat(llm, prompts.CODEGEN_SYSTEM,
                             prompts.repair_user(stage, feedback, lib_rs),
                             f"repair-{stage}-{repairs}")
            new_main = prompts.extract_rust(raw)
            if not new_main:
                return GenReport(False, spec=spec,
                                 failure=f"repair-{stage}: no rust block in reply")
            lib_rs = new_main

        # ---- gate D: gen_perf actually runs (separate phase, own budget) ----
        # Activity B, not A. smoke only exercises the tiny gen_seeds inputs, so
        # gen_perf itself is NEVER run during the loop above — a crashing /
        # oversized gen_perf ships broken perf inputs undetected. Verify it here
        # with its OWN repair budget, decoupled from the build/smoke/coverage
        # oscillation (which would otherwise starve it on hard crates). If it
        # still crashes after the budget, accept + warn: downstream perf
        # profiling already falls back to corpus inputs for the crashing op(s).
        # `lib_rs` entering here builds + smokes (the loop broke out on ok, or
        # reverted to the last build+smoke-passing checkpoint). `perf_safe_lib`
        # tracks the most recent build+smoke-passing version so we NEVER ship a
        # non-building harness if a perf-repair leaves it broken mid-loop.
        perf_safe_lib = lib_rs
        perf_ok, perf_fb = gates.gate_perf(hdir, spec)
        perf_stage = "perf"
        perf_repairs = 0
        perf_op_failures: dict[str, int] = {}
        while not perf_ok and perf_repairs < self.perf_repairs_max:
            # Same reasoning as the smoke loop, with one difference that makes
            # the remedy simpler: a crashing perf input is ALREADY handled
            # downstream. `profile_harness` ranks gen-perf inputs, their
            # truncations AND corpus inputs together; an input that crashes
            # probes as -1 and loses to a corpus candidate. So the end state
            # after exhausting the budget ("accepting; perf profiling salvages
            # the valid perf inputs") is the same state as giving up now —
            # every extra round is spent buying nothing. Measured: 3 of 3 perf
            # repairs went to one op and the run accepted anyway.
            perf_culprit = gates.failing_op(perf_fb) if perf_stage == "perf" else None
            if perf_culprit:
                perf_op_failures[perf_culprit] = perf_op_failures.get(perf_culprit, 0) + 1
                if perf_op_failures[perf_culprit] > self.max_op_repairs:
                    logger.warning(
                        "[harness_gen] op `%s` still crashes on its perf input"
                        " after %d attempt(s) — stopping here instead of"
                        " rewriting the whole harness again; profiling falls"
                        " back to a corpus input for it and every other op"
                        " keeps its perf target",
                        perf_culprit, perf_op_failures[perf_culprit] - 1)
                    break
            perf_repairs += 1
            logger.info("[harness_gen] gate %s failed → perf-repair %d/%d",
                        perf_stage, perf_repairs, self.perf_repairs_max)
            raw = self._chat(llm, prompts.CODEGEN_SYSTEM,
                             prompts.repair_user(perf_stage, perf_fb, lib_rs),
                             f"repair-perf-{perf_repairs}")
            new_main = prompts.extract_rust(raw)
            if not new_main:
                logger.warning("[harness_gen] perf-repair: no rust block; stopping")
                break
            lib_rs = new_main
            (hdir / "src" / "lib.rs").write_text(lib_rs, encoding="utf-8")
            # A perf-repair must not break build or the smoke oracle. If it
            # does, keep the right feedback and spend the next slot fixing it
            # (a broken oracle is worse than a crashing gen_perf, which is
            # salvaged by try_gen_perf's partial-output fallback).
            bok, bfb = gates.gate_build(
                hdir, rustflags="-C debug-assertions=off -C overflow-checks=off")
            if not bok:
                perf_fb, perf_stage = bfb, "build"
                continue
            sok, sfb = gates.gate_smoke(hdir, spec)
            if not sok:
                perf_fb, perf_stage = sfb, "smoke"
                continue
            perf_safe_lib = lib_rs        # builds + smokes → new safe fallback
            perf_ok, perf_fb = gates.gate_perf(hdir, spec)
            perf_stage = "perf"
        # Never ship a non-building/-smoking harness: if the loop ended on a
        # broken repair, restore the last build+smoke-passing version.
        if lib_rs != perf_safe_lib:
            lib_rs = perf_safe_lib
            (hdir / "src" / "lib.rs").write_text(lib_rs, encoding="utf-8")
            gates.gate_build(
                hdir, rustflags="-C debug-assertions=off -C overflow-checks=off")
        if perf_ok:
            logger.info("[harness_gen] gate perf OK — gen_perf runs "
                        "(%d perf-repair(s))", perf_repairs)
        else:
            logger.warning("[harness_gen] gen_perf not fully clean after %d "
                           "perf-repair(s) — accepting; perf profiling salvages "
                           "the valid perf inputs and uses corpus for the rest",
                           perf_repairs)

        # ---- persist ------------------------------------------------
        (logs_dir / "spec.json").write_text(
            json.dumps(spec, indent=2, ensure_ascii=False), encoding="utf-8")
        report = GenReport(True, harness_dir=str(hdir), spec=spec,
                           line_pct=cov.line_pct, fn_pct=cov.fn_pct,
                           uncovered=cov.uncovered or [],
                           llm_calls=self.llm_calls)
        (logs_dir / "report.json").write_text(json.dumps({
            "project": str(self.project_dir),
            "crate": inv.crate_name,
            "harness_dir": report.harness_dir,
            "operations": [op["name"] for op in spec["operations"]],
            "coverage": {"line_pct": round(cov.line_pct, 1),
                         "fn_pct": round(cov.fn_pct, 1),
                         "min_line": self.min_line, "min_fn": self.min_fn,
                         "uncovered_api_fns": cov.uncovered or [],
                         "internal_total": cov.internal_total,
                         "uncovered_internal_fns": cov.uncovered_internal or []},
            "llm_calls": self.llm_calls,
        }, indent=2), encoding="utf-8")
        return report

    def _plan(self, llm, inv: CrateInventory) -> dict[str, Any]:
        raw = self._chat(llm, prompts.PLAN_SYSTEM, prompts.plan_user(inv), "plan")
        spec = prompts.extract_json(raw)
        err = prompts.validate_spec(spec) if spec else "no JSON object in reply"
        if err:
            # one bounded retry with the validation error attached
            raw = self._chat(llm, prompts.PLAN_SYSTEM,
                             prompts.plan_user(inv)
                             + f"\n\nYour previous answer was rejected: {err}. "
                               f"Answer with ONE valid JSON object only.",
                             "plan-retry")
            spec = prompts.extract_json(raw)
            err = prompts.validate_spec(spec) if spec else "no JSON object in reply"
            if err:
                raise RuntimeError(f"plan failed: {err}")
        return spec
