[workspace]

[package]
name = "purebin_freeform"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "lz4_freeform"
path = "src/main.rs"

[dependencies]
lz4lib = { path = "../../../3_perf_opt_freeform/crate", package = "lz4_cleaned" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
