"""A fn whose link name differs from its source name must still resolve.

perf reports the LINK name. `build_fn_index` indexed only the source name, so
a function the linker knows by another name resolved to nothing and `locate`
dropped it into `unresolved_symbols` — the bucket meant for macro-generated
accessors that genuinely have no source to rewrite.

c2rust produces exactly this collision whenever the C identifier is a Rust
keyword: `match` cannot be a fn name, so it emits `fn match_0` carrying
`#[export_name = "match"]`. Measured on fzy, `match` is 13-16% of both
`choices_*` operations and was dropped from every run with
"dropped unresolved (no source location): ['match']". Its body holds the
26,632 bytes of zero-init that the C original never pays, so the one function
that was invisible was also the one with something to collect.

The genuine unresolvable case must keep being dropped: http-parser's
`status_code` is generated by `#[bitfield]` and has no `fn status_code` in the
source at all. Nothing here gives it a location.
"""

from __future__ import annotations

import pytest

from perf_opt.hot_probe.symbol_source import build_fn_index

pytest.importorskip("tree_sitter_rust")


def _crate(tmp_path, body: str):
    (tmp_path / "src").mkdir(parents=True, exist_ok=True)
    (tmp_path / "src" / "m.rs").write_text(body, encoding="utf-8")
    return build_fn_index(tmp_path)


def test_export_name_resolves_to_the_source_range(tmp_path) -> None:
    idx = _crate(tmp_path, '#[export_name = "match"]\nfn match_0() {}\n')
    assert idx.resolve("match") == idx.resolve("match_0") != None


def test_the_source_name_still_resolves(tmp_path) -> None:
    idx = _crate(tmp_path, '#[export_name = "match"]\nfn match_0() {}\n')
    loc = idx.resolve("match_0")
    assert loc is not None and loc[0] == "src/m.rs"


def test_link_name_joins_the_editable_set(tmp_path) -> None:
    """`names()` is what `locate` uses as `resolvable`."""
    idx = _crate(tmp_path, '#[export_name = "match"]\nfn match_0() {}\n')
    assert {"match", "match_0"} <= idx.names()


def test_it_survives_a_preceding_no_mangle(tmp_path) -> None:
    """Attributes are a run of preceding siblings, not just the nearest one."""
    idx = _crate(
        tmp_path, '#[no_mangle]\n#[export_name = "sym"]\nfn other() {}\n')
    assert idx.resolve("sym") is not None


def test_unquoted_spacing_variants_parse(tmp_path) -> None:
    idx = _crate(tmp_path, '#[export_name="tight"]\nfn a() {}\n')
    assert idx.resolve("tight") is not None


def test_a_plain_fn_gains_no_alias(tmp_path) -> None:
    idx = _crate(tmp_path, "fn plain() {}\n")
    assert idx.names() == {"plain"}


def test_no_mangle_alone_adds_nothing(tmp_path) -> None:
    """`#[no_mangle]` keeps the source name, so there is no second key."""
    idx = _crate(tmp_path, "#[no_mangle]\nfn same() {}\n")
    assert idx.names() == {"same"}


def test_an_absent_definition_stays_unresolvable(tmp_path) -> None:
    """http-parser's `#[bitfield]`-generated `status_code` must NOT resolve."""
    idx = _crate(tmp_path, "fn unrelated() {}\n")
    assert idx.resolve("status_code") is None


def test_the_attribute_of_a_LATER_fn_does_not_leak_backwards(tmp_path) -> None:
    idx = _crate(
        tmp_path,
        "fn first() {}\n#[export_name = \"second_sym\"]\nfn second() {}\n")
    assert idx.resolve("second_sym") == idx.resolve("second")
    assert idx.resolve("second_sym") != idx.resolve("first")


# ───────────────────────────── byte offsets are not character offsets

NON_ASCII_CRATE = (
    "fn early() {}\n"
    "// Applied rules: [III④, III③, C3, C1]\n"   # ③④ — written by us
    "fn after_the_marker() {}\n"
    "#[export_name = \"linked\"]\n"
    "fn also_after() {}\n"
)


def test_a_non_ascii_comment_does_not_corrupt_later_names(tmp_path) -> None:
    """The crate must not be able to poison its own index by being rewritten.

    tree-sitter offsets are BYTE offsets. Slicing the decoded `str` with them
    shifts by one position per non-ASCII character seen so far, cumulatively,
    so every fn below the first one comes out as garbage. The changeset writer
    records `// Applied rules: [III④, ...]` into the very files being indexed,
    so this fired on any crate the pipeline had already touched: on fzy,
    `match_row` / `match_positions` / `setup_match_struct` all sat below that
    comment and indexed under names like `'\\n    mut '`.
    """
    idx = _crate(tmp_path, NON_ASCII_CRATE)
    assert {"early", "after_the_marker", "also_after"} <= idx.names()


def test_export_name_still_resolves_after_non_ascii(tmp_path) -> None:
    idx = _crate(tmp_path, NON_ASCII_CRATE)
    assert idx.resolve("linked") == idx.resolve("also_after") is not None


def test_no_garbage_keys_survive(tmp_path) -> None:
    idx = _crate(tmp_path, NON_ASCII_CRATE)
    assert all(n.isidentifier() for n in idx.names()), sorted(idx.names())


def test_the_resolved_range_still_points_at_the_right_fn(tmp_path) -> None:
    """A shifted slice can also yield a plausible-looking wrong name."""
    idx = _crate(tmp_path, NON_ASCII_CRATE)
    loc = idx.resolve("also_after")
    assert "fn also_after" in idx.source(*loc)


# ───────────────────── the span lookup must accept the link name too

def _span_of(tmp_path, body: str, name: str, hint=(1, 99)):
    from perf_opt.agent_perf_opt.rewrite_applier import locate_fn_span_with_attrs
    f = tmp_path / "m.rs"
    f.write_text(body, encoding="utf-8")
    return f, locate_fn_span_with_attrs(f, name, hint_line_range=hint)


KEYWORD_FN = (
    "fn before() {}\n"
    '#[export_name = "match"]\n'
    "pub unsafe extern \"C\" fn match_0(a: i32) -> i32 { a }\n"
)


def test_span_lookup_accepts_the_link_name(tmp_path) -> None:
    """`resolve_edit_target` passes `hf.name`, which perf sets to the SYMBOL.

    Without this the agent logs "no editable target (D16/D17 path), skipping"
    and the function is never offered to the model at all — on fzy that was
    15.07% of `choices_fread_search`, holding the 26,632 bytes of zero-init
    the C original never pays.
    """
    _, span = _span_of(tmp_path, KEYWORD_FN, "match")
    assert span is not None


def test_link_name_and_source_name_give_the_same_span(tmp_path) -> None:
    _, a = _span_of(tmp_path, KEYWORD_FN, "match")
    _, b = _span_of(tmp_path, KEYWORD_FN, "match_0")
    assert a == b is not None


def test_the_span_swallows_the_export_name_attribute(tmp_path) -> None:
    """The attribute must be inside the replaced range, or a rewrite that
    omits it would silently drop the exported symbol."""
    f, span = _span_of(tmp_path, KEYWORD_FN, "match")
    assert span is not None
    assert f.read_bytes()[span[0]:span[1]].startswith(b'#[export_name')


def test_an_unrelated_name_still_finds_nothing(tmp_path) -> None:
    _, span = _span_of(tmp_path, KEYWORD_FN, "not_here")
    assert span is None


def test_a_plain_fn_is_unaffected(tmp_path) -> None:
    _, span = _span_of(tmp_path, KEYWORD_FN, "before")
    assert span is not None


def test_the_edit_target_is_named_as_the_source_names_it(tmp_path) -> None:
    """The FORM check compares the model's output against `EditTarget.fn_name`.

    Given the LINK name, the model is asked to reproduce `fn match` for a file
    that says `fn match_0`; it writes the correct source name and is refused —
    measured: "whole-fn reply refused on form: replacement_function_name:
    expected function match, got match_0".
    """
    from perf_opt.agent_perf_opt.rewrite_applier import locate_fn_span_and_name
    f = tmp_path / "m.rs"
    f.write_text(KEYWORD_FN, encoding="utf-8")
    found = locate_fn_span_and_name(f, "match", hint_line_range=(1, 99))
    assert found is not None and found[2] == "match_0"


def test_a_plain_fn_reports_its_own_name(tmp_path) -> None:
    from perf_opt.agent_perf_opt.rewrite_applier import locate_fn_span_and_name
    f = tmp_path / "m.rs"
    f.write_text(KEYWORD_FN, encoding="utf-8")
    found = locate_fn_span_and_name(f, "before", hint_line_range=(1, 99))
    assert found is not None and found[2] == "before"


def test_the_old_two_tuple_api_is_unchanged(tmp_path) -> None:
    """Other callers still get (start, end) — no behavioural drift."""
    from perf_opt.agent_perf_opt.rewrite_applier import (
        locate_fn_span_and_name, locate_fn_span_with_attrs,
    )
    f = tmp_path / "m.rs"
    f.write_text(KEYWORD_FN, encoding="utf-8")
    span = locate_fn_span_with_attrs(f, "match", hint_line_range=(1, 99))
    full = locate_fn_span_and_name(f, "match", hint_line_range=(1, 99))
    assert span == (full[0], full[1])
