[workspace]
members = [
]
[package]
name = "libopenaptx_cleaned"
authors = ["C2Rust"]
version = "0.0.0"
publish = false
edition = "2021"
autobins = false

[lib]
name = "libopenaptx_cleaned"
path = "lib.rs"
crate-type = ["staticlib", "rlib"]
[dependencies]

[[bin]]
path = "src/openaptxdec.rs"
name = "openaptxdec"

[[bin]]
path = "src/openaptxenc.rs"
name = "openaptxenc"
