[workspace]

[package]
name = "purebin_stage_a"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "libqrencode_stage_a"
path = "src/main.rs"

[dependencies]
qrlib = { path = "../../../2_stage_a/crate", package = "libqrencode_cleaned" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
