[workspace]

[package]
name = "purebin_full"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "libopenaptx_full"
path = "src/main.rs"

[dependencies]
libopenaptx = { path = "../../../3_perf_opt/crate", package = "libopenaptx_cleaned" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
