[workspace]

[package]
name = "purebin_raw"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "libqrencode_raw"
path = "src/main.rs"

[dependencies]
qrlib = { path = "../../../0_raw", package = "libqrencode_raw" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
