[workspace]

[package]
name = "purebin_codex"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "optipng_codex"
path = "src/main.rs"

[dependencies]
optipnglib = { path = "../../../codex_version/code", package = "optipng_0_7_7_raw" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
debug = false
